[project]
name = "simultons"
version = "0.1.0"
description = "Just playing with elevator simulation."
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "cmd2>=2.7.0",
    "fastapi-utils>=0.8.0",
    "fastapi[standard]>=0.115.14",
    "gnureadline>=8.2.13",
    "httpx>=0.28.1",
    "logging-tree>=1.10",
    "pyyaml>=6.0.2",
    "pyzmq>=27.0.0",
    "gnureadline; sys_platform == 'linux'",
    "starlette",
]

[dependency-groups]
# install these using `uv sync --group dev`
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.1",
    "types-pyyaml>=6.0.12.20250516",
    "typing-inspect>=0.9.0",
]

[project.scripts]
simultons = "simultons/__main__:main"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A001","A002","ANN401","ARG001",
    "B006","B011","BLE001",
    "C901","COM812",
    "D100","D101","D102","D103","D104","D107","D200","D202","D203","D205","D212","D400","D401","D415",
    "E501","EM102","ERA001",
    "FIX002",
    "FBT001",
    "G004",
    "Q000","Q003",
    "N801","N803","N806",
    "PT009","PT015","PLR0915","PLR1711","PLR0912","PLR0913","PLR2004","PLW0603",
    "RET505","RET507",
    "RUF022","RUF059",
    "S101","S603","SIM114","SLF001",
    "T201",
    "TD002","TD003",
    "TRY003","TRY300"
]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "logging_tree.*",
    "mypy-recurrent.*",
    "strip_ansi.*"
]
ignore_missing_imports = true
