#
# Simultons Software Settings
#
simulation:
  source: simultons/simulation.py
  #host: localhost
  port: 9100
  first_simulton_port: 9110
  #rate: 1
simultons:
  #host: localhost
  first_port: 9110
